version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-s3: circleci/aws-s3@3.0
  ruby: circleci/ruby@1.8
  slack: circleci/slack@4.1

workflows:
  test-deploy:
    jobs:
      - build
      - test
          requires:
            - build
      - slack/on-hold
          context: slack-secrets
          requires:
            - build
      - pause_workflow:
          requires:
            - test
            - slack/on-hold
          filters:
            branches:
              only: main
      - deploy:
          context: aws-s3-deploy
          requires:
            - pause_workflow
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6
    environment:
      BUNDLE_PATH: ~/project/vendor/bundle
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site

  test:
    docker:
      - image: cimg/ruby:2.7.6
    environment:
      BUNDLE_PATH: ~/project/vendor/bundle
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Jekyll build
          command: bundle exec jekyll build

  deploy:
    docker:
      - image: cimg/python:3.10.4
    environment:
      S3_BUCKET_NAME: demo-jekyll-oidc-s3
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          role-arn: arn:aws:iam::483285841698:role/demo-jekyll-oidc-role
      - aws-s3/sync:
          arguments: "--delete"
          from: ./_site
          to: "s3://$S3_BUCKET_NAME/"